### PR TITLE
added preserveDirectory option

### PR DESCRIPTION
**Pull request by yevgenys**
I added preserveDirectory option;
this option is optional;
the idea is next - if this flag is true, then each report will be created in separate directory, directory names are generated with hat()

P.S. - i'm new in JS so if i done some horrible mistakes please do not be mad on me :)

### CODE REVIEW

**Comment by mlison** [comment]
Looks reasonable - could you please update the [README.md](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/README.md) and (if you like) add yourself to list of contributors in [package.json](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/package.json)?

**Comment by yevgenys** [comment]
added description to readme and myself as contributor

**Comment by yevgenys** [comment]
probably was my mistake to close it :)

**Comment by mlison** [comment]
:+1:

**Pull request merged**
