### PR TITLE
Iterate over all parent suites as well as pass capabilities to pathBuilder

### PR DESCRIPTION
**Pull request by charandas**
It wasn't considering all the suites, just the first. This fixes it by iterating over all the suites.

### CODE REVIEW

**Comment by charandas** [comment]
@mlison Please take a look at this changeset. Let me know if I can update anything to get this merged sooner.

**Comment by mlison** [comment]
Thanks for your effort, the problem is that this will print out certain results multiple times in some versions of jasmine (depending on if your scenarios have common ancestor or not). I'm aware of this problem and I'll get it fixed as soon as I have some extra time.

**Comment by charandas** [comment]
@mlison I thought I addessed that issue in  my latest commit. I rebased my changes, so you may not have noticed. I am looking at `suite._parent` to decide whether to factor the test results for the suite. I am not in the hurry as I have resorted to using our local npm server to host my fork.

**Comment by mlison** [comment]
@kbdaitch I think v0.1.3 should fix this already (albeit a bit dirty). Lemme know if it still doesn't do the trick.

**Comment by charandas** [comment]
:+1:  @mlison Btw, this [line](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/index.js#L143) needs to be moved down to pass capabilities.

**Comment by mlison** [comment]
@kbdaitch good point, I'll put it on the list.

**Pull request closed without merging**
